spring.datasource:
  url: jdbc:h2:mem:testdb
  driverClassName: org.h2.Driver
  username: sa
  password:
spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

spring.jpa.show-sql: true

#  url: jdbc:h2:file:/Users/zaragozamr/coffee/trapcount/data

spring.h2.console:
  enable: true
  path: /h2-console
  settings:
    trace: false
    web-allow-others: false

logging.level:
  com: DEBUG
#  org.springframework: DEBUG